GET https://localhost:5001/products/ HTTP/1.1
### Get all product

GET https://localhost:5001/products/1 HTTP/1.1
### Get product by id

GET https://localhost:5001/products/111 HTTP/1.1
### Get product that doesn't exist

DELETE https://localhost:5001/products/1 HTTP/1.1
### Delete product by id
